from ..extensions import db


class Inventory(db.Model):
    __bind_key__ = "general"
    __tablename__ = "INVE01"

    # (PK)
    CVE_ART = db.Column(db.String, primary_key=True, nullable=False)

    # (DOUBLE PRECISION -> Float in SQLAlchemy)
    UNI_EMP = db.Column(db.Float)
    STOCK_MIN = db.Column(db.Float)
    STOCK_MAX = db.Column(db.Float)
    COMP_X_REC = db.Column(db.Float)
    PEND_SURT = db.Column(db.Float)
    EXIST = db.Column(db.Float)
    COSTO_PROM = db.Column(db.Float)
    ULT_COSTO = db.Column(db.Float)
    FAC_CONV = db.Column(db.Float)
    APART = db.Column(db.Float)
    PESO = db.Column(db.Float)
    VOLUMEN = db.Column(db.Float)
    VTAS_ANL_C = db.Column(db.Float)
    VTAS_ANL_M = db.Column(db.Float)
    COMP_ANL_C = db.Column(db.Float)
    COMP_ANL_M = db.Column(db.Float)
    LARGO_ML = db.Column(db.Float)
    ALTO_ML = db.Column(db.Float)
    ANCHO_ML = db.Column(db.Float)
    CUOTA_IEPS = db.Column(db.Float)
    FAC_UNID_CCE = db.Column(db.Float)

    # Dates
    FCH_ULTCOM = db.Column(db.DateTime)
    FCH_ULTVTA = db.Column(db.DateTime)
    F_CREA_ML = db.Column(db.DateTime)
    VERSION_SINC = db.Column(db.DateTime)
    VERSION_SINC_FECHA_IMG = db.Column(db.DateTime)

    # (VARCHAR)
    CATEG_ML = db.Column(db.String)
    LAST_UPDATE_ML = db.Column(db.String)
    ID_CATALOGO = db.Column(db.String)
    UNI_MED = db.Column(db.String)
    CTRL_ALM = db.Column(db.String)
    UNI_ALT = db.Column(db.String)
    ENVIO_ML = db.Column(db.String)
    UUID = db.Column(db.String)
    DESCR = db.Column(db.String)
    PREFIJO = db.Column(db.String)
    TALLA = db.Column(db.String)
    COLOR = db.Column(db.String)
    CVE_UNIDAD = db.Column(db.String)
    CVE_PUBL_ML = db.Column(db.String)
    TIPO_PUBL_ML = db.Column(db.String)
    CAMPOS_CATEG_ML = db.Column(db.String)
    CVE_CATE_ML = db.Column(db.String)
    TITULO_ML = db.Column(db.String)
    CUENT_CONT = db.Column(db.String)
    CVE_IMAGEN = db.Column(db.String)
    LIN_PROD = db.Column(db.String)
    CON_SERIE = db.Column(db.String)
    TIP_COSTEO = db.Column(db.String)
    TIPO_ELE = db.Column(db.String)
    CON_LOTE = db.Column(db.String)
    CON_PEDIMENTO = db.Column(db.String)
    CVE_PRODSERV = db.Column(db.String)
    EDO_PUBL_ML = db.Column(db.String)
    CONDICION_ML = db.Column(db.String)
    MODO_ENVIO_ML = db.Column(db.String)
    DISPONIBLE_PUBL = db.Column(db.String)
    EN_CATALOGO = db.Column(db.String)
    BLK_CST_EXT = db.Column(db.String)
    STATUS = db.Column(db.String)
    MAN_IEPS = db.Column(db.String)
    APL_MAN_IEPS = db.Column(db.String)
    UNI_ADUANA = db.Column(db.String)
    FRACC_ARANC = db.Column(db.String)

    # Integers
    TIEM_SURT = db.Column(db.Integer)
    NUM_MON = db.Column(db.Integer)
    CVE_OBS = db.Column(db.Integer)
    CVE_ESQIMPU = db.Column(db.Integer)
    CVE_BITA = db.Column(db.Integer)
    APL_MAN_IMP = db.Column(db.Integer)

    #  (BLOB)
    IMAGEN_ML = db.Column(db.BLOB)
    # MAT_PELI = db.Column(db.LargeBinary)
    DESC_ESPECIFICA = db.Column(db.BLOB)
