package com.bamx.backend.dtos;

import java.time.LocalDateTime;
import lombok.Builder;
import lombok.Data;

@Data
@Builder
public class InveDto {
  private String cveArt;
  private String descr;
  private String linProd;
  private String conSerie;
  private String uniMed;
  private Double uniEmp;
  private String ctrlAlm;
  private Integer tiemSurt;
  private Double stockMin;
  private Double stockMax;
  private String tipCosteo;
  private Integer numMon;
  private LocalDateTime fchUltCom;
  private Double compXRec;
  private LocalDateTime fchUltVta;
  private Double pendSurt;
  private Double exist;
  private Double costoProm;
  private Double ultCosto;
  private Integer cveObs;
  private String tipoEle;
  private String uniAlt;
  private Double facConv;
  private Double apart;
  private String conLote;
  private String conPedimento;
  private Double peso;
  private Double volumen;
  private Integer cveEsqImpu;
  private Integer cveBita;
  private Double vtasAnlC;
  private Double vtasAnlM;
  private Double compAnlC;
  private Double compAnlM;
  private String prefijo;
  private String talla;
  private String color;
  private String cuentCont;
  private String cveImagen;
  private String blkCstExt;
  private String status;
  private String manIeps;
  private Integer aplManImp;
  private Double cuotaIeps;
  private String aplManIeps;
  private String uuid;
  private LocalDateTime versionSinc;
  private LocalDateTime versionSincFechaImg;
  private String cveProdServ;
  private String cveUnidad;
  private String edoPublMl;
  private String cvePublMl;
  private String condicionMl;
  private String tipoPublMl;
  private String modoEnvioMl;
  private Double largoMl;
  private Double altoMl;
  private Double anchoMl;
  private String envioMl;
  private String categMl;
  private String camposCategMl;
  private String disponiblePubl;
  private String cveCateMl;
  private String lastUpdateMl;
  private LocalDateTime f_CreaMl;
  private String imagenMl;
  private String idCatalogo;
  private String enCatalogo;
  private String tituloMl;
  private String matPeli;
}
