spring.application.name=backend
spring.datasource.empresa.driver-class-name=org.firebirdsql.jdbc.FBDriver
spring.datasource.auth.driver-class-name=org.firebirdsql.jdbc.FBDriver
spring.datasource.empresa.url=jdbc:firebirdsql://localhost:3050/C:/Program Files (x86)/Common Files/Aspel/Sistemas Aspel/SAE8.00/Ejemplos/Ejemplos.fdb?encoding=WIN1252
spring.datasource.auth.url=jdbc:firebirdsql://localhost:3050/C:/Program Files (x86)/Common Files/Aspel/Perfiles/PERFILES.FDB?encoding=WIN1252
spring.datasource.empresa.username=sysdba
spring.datasource.empresa.password=masterkey
spring.datasource.auth.username=sysdba
spring.datasource.auth.password=masterkey
spring.jpa.open-in-view=true
spring.jpa.hibernate.ddl-auto=validate

# jwt properties
jwt.secret=${JWT_SECRET}
jwt.access-token-expiration=${ACCESS_TOKEN_EXPIRATION}
jwt.refresh-token-expiration=${REFRESH_TOKEN_EXPIRATION}

bamx.refrigeradores=1
