spring.application.name=backend
spring.datasource.empresa.driver-class-name=org.firebirdsql.jdbc.FBDriver
spring.datasource.auth.driver-class-name=org.firebirdsql.jdbc.FBDriver
spring.datasource.empresa.url=jdbc:firebirdsql://${DATABASE_HOST_EMPRESA}:${DATABASE_PORT_EMPRESA}/${DATABASE_PATH_EMPRESA}?encoding=WIN1252
spring.datasource.auth.url=jdbc:firebirdsql://${DATABASE_HOST_AUTH}:${DATABASE_PORT_AUTH}/${DATABASE_PATH_AUTH}?encoding=WIN1252
spring.datasource.empresa.username=sysdba
spring.datasource.empresa.password=masterkey
spring.datasource.auth.username=sysdba
spring.datasource.auth.password=masterkey
spring.jpa.open-in-view=true
spring.jpa.hibernate.ddl-auto=validate

app.images.path=${APP_IMAGES_PATH}
app.host.url=${APP_HOST_URL}

# jwt properties
jwt.secret=${JWT_SECRET}
jwt.access-token-expiration=${ACCESS_TOKEN_EXPIRATION}
jwt.refresh-token-expiration=${REFRESH_TOKEN_EXPIRATION}
# server properties
server.address=0.0.0.0
# bamx properties
bamx.refrigeradores=3
