name: Backend Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
        name: Set up Python
      - run: pip install -r requirements.txt
        name: Run Tests
      - run: |
          export PYTHONPATH="$PYTHONPATH:$(pwd)"
          pytest --maxfail=1 --disable-warnings -q --cov=. --cov-report=xml --cov-report=term
      - uses: codecov/codecov-action@v4
        with:
          files: ./backend/coverage.xml
          flags: backend
          fail_ci_if_error: true
