name: Frontend Tests

on:
  pull_request:
    branches: [main]

jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/**'

      - name: Install Dependencies
        if: contains(steps.filter.outputs.changes, 'frontend')
        run: |
          cd frontend
          npm install
      - name: Run Frontend Tests
        if: contains(steps.filter.outputs.changes, 'frontend')
        run: |
          cd frontend
          npm run test

      - name: Upload Coverage to Codecov
        if: contains(steps.filter.outputs.changes, 'frontend')
        uses: codecov/codecov-action@v4
        with:
          directory: ./frontend/coverage
          flags: frontend
          fail_ci_if_error: true
